export const fundamentalFrequencyParamsStruct = `struct FundamentalFrequencyParams {
  halfSize: u32,
  windowCount: u32,
  windowSize: u32,
  candidateCount: u32,
  sampleRate: f32,
  minimumFrequency: f32,
  candidateStepCents: f32,
  harmonicCount: u32,
  slotOffset: u32,
  columnCount: u32,
  screenBase: u32,
  baseSlot: u32,
  latticeCount: u32,
  trackWindow: u32,
  peakSeparationCents: f32,
  loudnessExponent: f32,
  fundamentalWeight: f32,
  antiWeight: f32,
  jumpCostCents: f32,
  jumpCapCents: f32,
  unvoicedCost: f32,
  voicedTransitionCost: f32,
};`;
