allow-expect-in-tests = true
allow-panic-in-tests = true
allow-unwrap-in-tests = true
cognitive-complexity-threshold = 15
excessive-nesting-threshold = 4
too-many-arguments-threshold = 4
too-many-lines-threshold = 100
