name: Repo Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EDITORCONFIG_CHECKER_VERSION: v4.0.1
  JSCPD_VERSION: 5.1.2

jobs:
  check-repo-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check duplicate code
        run: |
          curl -fsSL --output "$RUNNER_TEMP/jscpd.tar.gz" "https://github.com/kucherenko/jscpd/releases/download/v$JSCPD_VERSION/jscpd-linux-x64-gnu.tar.gz"
          tar -xzf "$RUNNER_TEMP/jscpd.tar.gz" -C "$RUNNER_TEMP"
          "$RUNNER_TEMP/jscpd" packages --config .jscpd.json
      - name: Check EditorConfig
        run: |
          curl -fsSL --output "$RUNNER_TEMP/editorconfig-checker.tar.gz" "https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$EDITORCONFIG_CHECKER_VERSION/editorconfig-checker-linux-amd64.tar.gz"
          tar -xzf "$RUNNER_TEMP/editorconfig-checker.tar.gz" -C "$RUNNER_TEMP"
          "$RUNNER_TEMP/editorconfig-checker"
